late double sellPrice;
late double sellBuyPrice;
late double sellQuantity;
double capitalGainTaxPercentage = 7.5;
late double sellTotalvalue;
late double sellSebonFee;
late double sellBrokerCommission;
late double sellCapitalGainTax;
late double profitOrLoss;
late double returnOnInvestment;
late double sellTotalReceivable;
bool isSellCalculation = false;
